export const PATHS = {
  home: "/",
  collections: "/collections",
  collection: (handle: string) => `/collections/${handle}`,
  product: (handle: string) => `/products/${handle}`,
  cart: "/cart",
  checkout: "/checkout",
  wishlist: "/wishlist",
  search: "/search",
  account: "/account",
  about: "/about",
  contact: "/contact",
  rooms: "/rooms",
  trackOrder: "/track-order",
  bulkInquiry: "/bulk-inquiry",
  sellWithUs: "/sell-with-us",
  policy: (handle: string) => `/policies/${handle}`,
  notFound: "*",
} as const;
